sudo: required

services:
  - docker

language: ruby

env:
  - TAG=registry.heroku.com/takuti-twitter-bot/web

before_install:
  - docker build -t $TAG .
  - docker run -it -d -p 9292:80 $TAG
  - docker ps -a
  - docker run -it $TAG /bin/sh -c "bundle exec rake test"

script:
  - curl localhost:9292

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com;
    docker push $TAG;
    fi
